// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_block: dynamic(() => import("./CtaBlock")),
  full_width_cta: dynamic(() => import("./FullWidthCta")),
  hero: dynamic(() => import("./Hero")),
  split_image_text: dynamic(() => import("./SplitImageText")),
  testimonials: dynamic(() => import("./Testimonials")),
};
